### ISSUE TITLE
can't access elements with desendants

### ISSUE THREAD

**Issue by guyvanbael** [silverstripe/silverstripe-elemental#233]
i want to query all elements (and there descendants) from a specific page, but somehow it only returns the baselement. This is the query. i can't use the __typename together with ... on xxx after the element.
Graphiql does however generate a query readBlocks which DOES give you acces to the descendants, but then again. In this query, i can't filter on pageID.
```graphql
{
  readElementPages(ID:1) {
          MenuTitle
          ElementalArea {
            Elements {
              edges {
                node {
                  Title
                  ClassName
                } 
              }
            }
          }
      }
    }
```

### Core versions

```
            "name": "silverstripe/graphql",
            "version": "1.1.0",
            "source": {
                "type": "git",
                "url": "https://github.com/silverstripe/silverstripe-graphql.git",
                "reference": "4a7a972b1ed81bea53727d4373e8ad56694e6510"
                
                        "name": "silverstripe/recipe-core",
            "version": "1.1.0",
            "source": {
                "type": "git",
                "url": "https://github.com/silverstripe/recipe-core.git",
                "reference": "2ea41ab93589a34e492030367369457cca665ae6"
            },    
```

### GraphQL configuration

```yaml
---
Name: api-graphql
After:
  - graphqlconfig
---
SilverStripe\GraphQL\Controller:
  cors:
    Enabled: true
    Allow-Origin: '*'
    Allow-Headers: 'Authorization, Content-Type'
    Allow-Methods:  'GET, POST, OPTIONS'
    Max-Age: 86400
  schema:
    scaffolding:
      types:
        DNADesign\Elemental\Models\BaseElement:
          fields: '*'
          operations:
            read:
              paginate: false
          nestedQueries:
            Personas: true
        TextImageLeft:
          fields: '*'
          operations:
            read: true
          nestedQueries:
            Personas: true
        TextImageRight:
          fields: '*'
          operations:
            read: true
          nestedQueries:
            Personas: true
        DNADesign\Elemental\Models\ElementContent:
          fields: '*'
          operations:
            read: true
        SharpspringPersona:
          fields: '*'
          operations:
            read: true
        DNADesign\Elemental\Models\ElementalArea:
          fields: '*'
          operations:
            read: true
          nestedQueries:
            Elements: true
        ElementPage:
          fields: '*'
          operations:
            read:
              args:
                ID: ID!
              paginate: false
```
